CREATE TABLE MATA_KULIAH
(
	Kode CHAR(10) PRIMARY KEY NOT NULL,
	Nama VARCHAR(100) NOT NULL,
	Prasyarat_Dari CHAR(10) REFERENCES MATA_KULIAH(Kode) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TERM
(
	Tahun INT NOT NULL,
	Semester INT NOT NULL,
	PRIMARY KEY (Tahun, Semester)
);

CREATE TABLE KELAS_MK
(
	IDKelasMK INT PRIMARY KEY NOT NULL,
	Tahun INT NOT NULL ,
	Semester INT NOT NULL,
	Kode_MK CHAR(10) NOT NULL,
	FOREIGN KEY (Tahun, Semester) REFERENCES TERM(Tahun, Semester) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (Kode_MK) REFERENCES MATA_KULIAH(Kode) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE DOSEN
(
	NIP VARCHAR(20) PRIMARY KEY NOT NULL,
	Nama VARCHAR(100) NOT NULL,
	Username VARCHAR(30) NOT NULL,
	Password VARCHAR(20) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Universitas VARCHAR(100) NOT NULL,
	Fakultas VARCHAR(100) NOT NULL
);

CREATE TABLE MAHASISWA
(
	NPM CHAR(10) PRIMARY KEY NOT NULL,
	Nama VARCHAR(100) NOT NULL,
	Username VARCHAR(30) NOT NULL,
	Password VARCHAR(20) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Email_Aktif VARCHAR(100),
	Waktu_Kosong VARCHAR(100),
	Bank VARCHAR(100),
	Norekening VARCHAR(100),
	Url_Mukatab VARCHAR(100),
	Url_Foto VARCHAR(100)
);

CREATE TABLE TELEPON_MAHASISWA
(
	NPM CHAR(10) NOT NULL REFERENCES MAHASISWA(NPM) ON DELETE CASCADE ON UPDATE CASCADE,
	Nomortelepon VARCHAR(20) NOT NULL,
	PRIMARY KEY (NPM, Nomortelepon)
);

CREATE TABLE MHS_MENGAMBIL_KELAS_MK
(
	NPM CHAR(10) NOT NULL REFERENCES MAHASISWA(NPM) ON DELETE CASCADE ON UPDATE CASCADE,
	IDKelasMK INT NOT NULL REFERENCES KELAS_MK(IDKelasMK) ON DELETE CASCADE ON UPDATE CASCADE,
	Nilai NUMERIC(5,2),
	PRIMARY KEY (NPM, IDKelasMK)
);

CREATE TABLE DOSEN_KELAS_MK
(
	NIP VARCHAR(20) NOT NULL,
	IDKelasMK INT NOT NULL,
	PRIMARY KEY (NIP, IDKelasMK),
	FOREIGN KEY (NIP) REFERENCES DOSEN(NIP) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IDKelasMK) REFERENCES KELAS_MK(IDKelasMK) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE LOWONGAN
(
	IDLowongan INT NOT NULL,
	IDKelasMK INT NOT NULL,
	Status BOOLEAN DEFAULT FALSE NOT NULL,
	Jumlah_Asisten INT DEFAULT 0 NOT NULL,
	Syarat_Tambahan VARCHAR(100),
	NIPDosenPembuka VARCHAR(20) NOT NULL,
	PRIMARY KEY (IDLowongan),
	FOREIGN KEY (IDKelasMK) REFERENCES KELAS_MK(IDKelasMK) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (NIPDosenPembuka) REFERENCES DOSEN(NIP) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE STATUS_LAMARAN 
(
	ID INT NOT NULL,
	Status VARCHAR(10) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE LAMARAN
(
	IDLamaran INT NOT NULL,
	NPM CHAR(10) NOT NULL,
	IDLowongan INT NOT NULL,
	ID_st_lamaran INT NOT NULL,
	IPK numeric(5,2) NOT NULL,
	JumlahSKS INT NOT NULL,
	NIP VARCHAR(20),
	PRIMARY KEY (IDLamaran, NPM),
	FOREIGN KEY (NPM) REFERENCES MAHASISWA(NPM) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IDLowongan) REFERENCES LOWONGAN(IDLowongan) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (ID_st_lamaran) REFERENCES STATUS_LAMARAN(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (NIP) REFERENCES DOSEN(NIP) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE  TABLE STATUS_LOG 
(
	ID INT NOT NULL,
	Status VARCHAR(10) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE KATEGORI_LOG
(
	ID INT NOT NULL,
	Kategori VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE LOG
(
	IDLog INT NOT NULL,
	IDLamaran INT NOT NULL,
	NPM CHAR(10) NOT NULL,
	ID_kat_log INT NOT NULL,
	ID_st_log INT NOT NULL,
	Tanggal DATE NOT NULL,
	Jam_Mulai TIME NOT NULL,
	Jam_Selesai TIME NOT NULL,
	Deskripsi_Kerja VARCHAR(100) NOT NULL,
	PRIMARY KEY (IDLog),
	FOREIGN KEY (IDLamaran, NPM) REFERENCES LAMARAN(IDLamaran, NPM) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (ID_kat_log) REFERENCES KATEGORI_LOG(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (ID_st_log) REFERENCES STATUS_LOG(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
