INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0001', 'Basis Data', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0002', 'Sistem Cerdas', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0003', 'Statistika dan Probabilitas', 'MK0002');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0004', 'Dasar-Dasar Pemrograman', 'MK0004');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0005', 'Struktur Data dan Algoritma', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0006', 'Aljabar Linier', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0007', 'Sistem Operasi', 'MK0008');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0008', 'Pemrograman Sistem', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0009', 'Jaringan Komputer', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0010', 'Pengantar Organisasi Komputer', 'MK0007');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0011', 'nembsd nasme', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0012', 'sit amet', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0013', 'morbi a ipsum', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0014', 'morbi quis', 'MK0003');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0015', 'justo aliquam', 'MK0007');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0016', 'nulla', 'MK0003');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0017', 'consequat nulla', 'MK0024');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0018', 'volutpat in', 'MK0028');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0019', 'libero', 'MK0033');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0020', 'erat quisque', 'MK0010');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0021', 'ligula in lacus', 'MK0034');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0022', 'orci luctus et', 'MK0029');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0023', 'est congue', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0024', 'cursus id turpis', 'MK0032');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0025', 'pretium quis lectus', 'MK0022');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0026', 'nec sem', 'MK0034');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0027', 'sed tristique', 'MK0011');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0028', 'nulla pede', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0029', 'magnis dis parturient', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0030', 'sapien', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0031', 'posuere', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0032', 'pretium iaculis diam', 'MK0015');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0033', 'congue', 'MK0022');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0034', 'sed tristique in', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0035', 'curabitur', 'MK0007');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0036', 'augue', 'MK0014');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0037', 'dui', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0038', 'nisi venenatis', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0039', 'morbi a ipsum', 'MK0023');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0040', 'elit sodales scelerisque', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0041', 'neque duis bibendum', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0042', 'est congue', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0043', 'morbi odio odio', 'MK0015');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0044', 'gravida', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0045', 'tincidunt', 'MK0017');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0046', 'lobortis convallis', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0047', 'sagittis', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0048', 'non', 'MK0025');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0049', 'lacinia aenean sit', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0050', 'lacinia nisi', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0051', 'leo', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0052', 'amet turpis elementum', 'MK0036');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0053', 'orci', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0054', 'ipsum integer a', 'MK0006');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0055', 'at turpis donec', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0056', 'porttitor id', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0057', 'mollis molestie', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0058', 'aliquam', 'MK0008');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0059', 'velit nec', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0060', 'magna', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0061', 'lobortis ligula', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0062', 'vehicula consequat', 'MK0012');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0063', 'massa', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0064', 'tortor risus dapibus', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0065', 'quisque porta', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0066', 'ante vel ipsum', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0067', 'accumsan odio', 'MK0014');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0068', 'sem duis aliquam', 'MK0032');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0069', 'penatibus et', 'MK0036');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0070', 'fusce', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0071', 'congue', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0072', 'eu mi', 'MK0026');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0073', 'vestibulum rutrum rutrum', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0074', 'nisi venenatis', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0075', 'odio consequat varius', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0076', 'est congue', 'MK0006');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0077', 'amet', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0078', 'pede justo eu', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0079', 'eu est congue', 'MK0026');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0080', 'lectus', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0081', 'id mauris', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0082', 'ultrices posuere', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0083', 'nascetur ridiculus', 'MK0035');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0084', 'erat nulla tempus', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0085', 'in', 'MK0011');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0086', 'scelerisque mauris', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0087', 'ultrices', 'MK0003');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0088', 'turpis nec euismod', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0089', 'eget elit sodales', 'MK0019');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0090', 'pede venenatis non', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0091', 'odio curabitur convallis', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0092', 'etiam vel augue', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0093', 'augue vestibulum', 'MK0013');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0094', 'ac', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0095', 'vel ipsum praesent', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0096', 'in', 'MK0018');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0097', 'mauris laoreet', '');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0098', 'viverra dapibus', 'MK0023');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0099', 'cras in purus', 'MK0030');
INSERT INTO MATA_KULIAH (Kode, Nama, Prasyarat_Dari) VALUES ('MK0100', 'eleifend', '');
